const ButtonsContainer = () => {
  const buttonNames = ["AC", "C", "%", "^", "!", "/", "7", "8", "9", "*", "4", "5", "6", "-", "1", "2", "3", "+", "0", ".", "=", "e", "(", ")", "sin", "cos", "tan", "log", "sqrt", "pi"];

  return (
    <div className="buttons-container">
      {buttonNames.map((name) => <button key={name} className="button">{name}</button>)}
    </div>
  );
};

export default ButtonsContainer;

Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, natus. Provident rerum dolorem in sunt sint modi temporibus adipisci molestias. Consectetur blanditiis qui a fuga sequi dignissimos libero magni, aut fugit, eum sapiente ipsa voluptate, aspernatur incidunt. Eos porro repellendus quos laudantium labore nostrum modi, obcaecati unde autem fugit, beatae dolore, enim corporis dolorum nam. Inventore placeat consequatur nisi in, earum perspiciatis at vitae beatae ullam quos optio modi veniam? Odit sint dolores error nesciunt voluptatem aliquid quia, eligendi atque? Voluptate omnis ut quam ullam nobis porro nihil delectus aliquid rerum voluptatibus fuga aperiam maxime animi sequi, veritatis atque, similique totam deleniti at quis! Dolores iste eveniet dolore cupiditate, rerum assumenda nostrum doloremque reiciendis. Fugit, debitis provident! Exercitationem at aliquid rerum. Molestiae odio, quas impedit in enim aspernatur omnis provident nemo explicabo, officia, odit ex. Eveniet libero voluptatum adipisci deserunt corporis ducimus, placeat vero cumque ullam! Praesentium exercitationem aut ipsum beatae aliquid minus repellendus magnam omnis voluptatibus! Numquam molestiae praesentium commodi doloribus facilis id sunt dignissimos quod quam quisquam ratione dolores placeat, aperiam fugiat odit autem distinctio non laboriosam magnam natus, eos vitae! Dolorem, aperiam veniam earum maiores consequuntur perspiciatis nam nisi incidunt delectus cumque? Voluptate ullam illo error laborum ad amet perspiciatis cum nemo vitae modi magni, maiores non autem eos, nobis quo corrupti neque similique quis aut aliquid. Ipsum, debitis aspernatur iusto iste eius esse qui natus fugit ullam corporis fuga magnam quam. Excepturi minus rerum, deleniti itaque rem eveniet sit necessitatibus inventore nesciunt ex, distinctio quos commodi est aliquid sint ad amet porro, expedita culpa recusandae dolores magni harum! Unde nulla et inventore laboriosam ut similique rerum fugit, iste sequi distinctio nesciunt quidem velit repudiandae doloremque numquam magnam provident, cupiditate eveniet impedit beatae labore cumque maxime odio? Veritatis ratione laudantium fugiat iusto iste perspiciatis cupiditate aspernatur. Explicabo dolore quam modi sequi delectus ullam architecto aspernatur enim excepturi nulla cumque fuga incidunt porro in possimus facere unde dolores distinctio, maxime eos expedita eius magni esse. Voluptas repudiandae ipsam neque dolorem ut velit excepturi inventore maxime repellendus aliquam eaque quidem temporibus quo corpor